import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeInitializer } from "./Utilities/ThemeInitializer";
import Header from "../components/organisms/header"
import { SideMenu } from "@/components/organisms/sidemenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ThemeInitializer is just a logic */}
        <ThemeInitializer /> 
        <Header />
        <SideMenu />
        {children} {/* page.tsx renders here automaticlly */} 
        {/* in hamin <router-outlet> hast, ke default page.tsx ro home mikhone */}
      </body>
    </html>
  );
}
